name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
      uses: subosito/flutter_action_setup@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
      - run: flutter --version


      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Android)
        run: flutter build apk --release 

    
